### ISSUE TITLE
What about the 5.10.x kernels?

### ISSUE THREAD

**Issue by Kwaskoff** [OE4T/linux-tegra-4.9#21]
5.10 is LTS release
How I can build it?
Why you don't build it already?

**Comment by JakeSays** [comment]
Rumor has it that nvidia is working on ubuntu 20.04, but it won't be released until late next year, and as far as I know there has been no mention of a new kernel.

Personally I could care less about the userland. A modern kernel is far more important to me.

**Comment by madisongh** [comment]
If you don't care about compatibility with the L4T BSP, CUDA, and NVIDIA's graphics support for the Jetsons, you can try building and booting the upstream Linux kernel on at least some of the Jetsons.  A Google search on `Jetson upstream kernel` should turn up some links.

This repo tracks the kernel in the NVIDIA-supplied BSP, which is likely to remain at a 4.9 base for a while.  There are a bunch of Android patches and not-yet-upstreamed drivers from NVIDIA that the rest of the BSP depends on, and since much of the BSP is binary-only, it would be difficult, if not impossible, to put together an upstream kernel that would be compatible.

**Comment by JakeSays** [comment]
@madisongh well, given that we're using the nano for its superior graphics capabilities not having nvidia's graphics support turns the nano in to a brick.

I don't understand why nvidia hasn't upgraded kernels by now. I don't care if it's upstream. I don't care if the BSP is opensource or not. I just want kernel that supports modern drivers. In other words, as the customer, I want the full value that I paid for.

Also, what does Android have to do with this?

**Comment by Kwaskoff** [comment]
Looks like bad support
proprietary bullshit =(

**Comment by JakeSays** [comment]
@Kwaskoff Proprietary or not is not an issue for me. However I do expect things to be kept current.

**Comment by nicolas-s** [comment]
5.10 expected for Developper preview Q1 2022
https://developer.nvidia.com/embedded/develop/roadmap

**Comment by JoeZhang-tn** [comment]
Any update?

**Comment by paralin** [comment]
Current 4.9.x does not even work with systemd anymore:

../src/basic/ether-addr-util.h:5:10: fatal error: net/ethernet.h: No such file or directory
    5 | #include <net/ethernet.h>
      |          ^~~~~~~~~~~~~~~~

as of v250

**Comment by paralin** [comment]
I've started the work to merge + test up to at least the latest 4.9.x kernels - currently have done up to 4.9.254 -

https://github.com/skiffos/linux/tree/jetson-wip

if anyone else wants to help test + stabilize this, I want to upgrade it eventually all the way up to 5.x (it's a far fetched dream I know)

**Comment by paralin** [comment]
Docker with cgroup v2 doesn't work with newer versions:

https://github.com/opencontainers/runc/issues/2959#issuecomment-847521031

... requires at least kernel 4.15

**Comment by paralin** [comment]
Merged & tested up to the latest 4.9.x - 4.9.307!

if anyone else wants to help test + stabilize this, I'm going to keep that branch up to date and try merging it with more recent kernels as well.

https://github.com/skiffos/linux/tree/skiff-jetson-4.9.x

https://github.com/skiffos/skiffos

![image](https://user-images.githubusercontent.com/534887/159145765-a625405e-7952-4718-8fae-f23457dd5a8f.png)

**Comment by woachk** [comment]
Maybe time to close that issue now...

**Comment by paralin** [comment]
No support for Jetson tx2 or nano?...

**Comment by woachk** [comment]
Nano code isn’t gone, and the nvgpu commit reverting GP10B commits can be reverted.. 

So might be worth a try

**Comment by JakeSays** [comment]
So now that this issue is closed, does that mean a modern kernel is available?

**Comment by woachk** [comment]
Yes, present in L4T 34.1 onwards.

**Comment by JakeSays** [comment]
@woachk i thought 34.1 was still 4.9. That's not modern.

**Comment by woachk** [comment]
34.x uses the 5.10.x kernel release.

https://github.com/OE4T/linux-tegra-5.10

**Comment by JakeSays** [comment]
@woachk oh! excellent! i gladly stand corrected:)

**Comment by paralin** [comment]
@woachk According to what I've read, the new jetpack version uses the 5.10.x kernel, but does not support jetson tx2 or nano or anything prior to that. They say to continue using 34.x which is kernel 4.9.x.

So that 5.10.x kernel doesn't support tx2, tx2i, nano, etc.

Right? Or am I wrong on this?

**Comment by woachk** [comment]
It’s not promised by NVIDIA, but no Tegra X1 support code was removed. For Tegra X2, nvgpu support for gp10b was removed, so it’s indeed a harder matter there.

**Comment by JakeSays** [comment]
@woachk ok so just so I understand, 5.10 with gpu support is **not** available for the nano?

**Comment by woachk** [comment]
no Tegra X1 support code was removed on the kernel side, so while it's not officially supported by nvidia, it could very well work.

**Comment by JakeSays** [comment]
@woachk I can't remember the answer to this, but the nano's are tegra X1 based?
