### ISSUE TITLE
The /proc/sys/kernel/sched_rt_runtime_us does not work ?

### ISSUE THREAD

**Issue by h2cw2l** [OE4T/linux-tegra-4.9#37]
@gebi @awilliam @augustl @mpalmer 

**[environment]**
Linux EAXVA05_B 4.9.253-tegra #27 SMP PREEMPT Wed May 18 17:58:14 CST 2022 aarch64 aarch64 aarch64 GNU/Linux

**[question description]**
question 1:
As we know, the default value of  /proc/sys/kernel/sched_rt_period_us is 1000000, /proc/sys/kernel/sched_rt_runtime_us is 950000.
When I run a thread with sched policy SCHED_FIFO and another thread with the default sched policy，the two threads are bond to the same cpu core. We cal the first thread thread1 and call the second thread thread2 below.

**We should see the thread1 use cpu 95% and thread2 5%， but I see the thread1 cpu 100%, thread2 0% ？** **Whats the reason, how to solve it ?**

question 2:
When I set /proc/sys/kernel/sched_rt_runtime_us smaller than 950000, it failed with "Invalid argument". How to solve it ?

question 1 test code:
```
#define _GNU_SOURCE
#include <errno.h>
#include <linux/kernel.h>
#include <linux/types.h>
#include <linux/unistd.h>
#include <pthread.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/syscall.h>
#include <sys/types.h>
#include <time.h>
#include <unistd.h>

#define gettid() syscall(__NR_gettid)

#define SCHED_DEADLINE 6

/* XXX use the proper syscall numbers */
#ifdef __x86_64__
#define __NR_sched_setattr 314
#define __NR_sched_getattr 315
#endif

#ifdef __i386__
#define __NR_sched_setattr 351
#define __NR_sched_getattr 352
#endif

#ifdef __arm__
#define __NR_sched_setattr 380
#define __NR_sched_getattr 381
#endif

static volatile int done;

struct sched_attr {
  __u32 size;

  __u32 sched_policy;
  __u64 sched_flags;

  /* SCHED_NORMAL, SCHED_BATCH */
  __s32 sched_nice;

  /* SCHED_FIFO, SCHED_RR */
  __u32 sched_priority;

  /* SCHED_DEADLINE (nsec) */
  __u64 sched_runtime;
  __u64 sched_deadline;
  __u64 sched_period;
};

int sched_setattr(pid_t pid, const struct sched_attr *attr, unsigned int flags) {
  return syscall(__NR_sched_setattr, pid, attr, flags);
}

int sched_getattr(pid_t pid, struct sched_attr *attr, unsigned int size, unsigned int flags) {
  return syscall(__NR_sched_getattr, pid, attr, size, flags);
}

int32_t SetAffinity() {
  cpu_set_t cpuset;
  CPU_ZERO(&cpuset);
  CPU_SET(1, &cpuset);

  if (pthread_setaffinity_np(pthread_self(), sizeof(cpuset), &cpuset) != 0) {
    printf("set affinity error, %s\n", strerror(errno));
    return -1;
  }
  return 0;
}

void *run_fifo(void *data) {
  struct sched_attr attr;
  int x = 0;
  int ret;
  unsigned int flags = 0;

  SetAffinity();

  attr.size = sizeof(attr);
  attr.sched_flags = 0;
  attr.sched_nice = 0;
  attr.sched_priority = 0;

  attr.sched_policy = SCHED_FIFO;
  attr.sched_priority = 90;

  ret = sched_setattr(gettid(), &attr, flags);
  if (ret < 0) {
    done = 0;
    perror("sched_setattr");
    exit(-1);
  }

  while (!done) {
    x++;
  }

  return NULL;
}

void *run_other(void *data) {
  int x = 0;
  SetAffinity();
  while (!done) {
    x++;
  }
  return NULL;
}

int main(int argc, char **argv) {
  pthread_t thread;

  printf("main thread [%ld]\n", gettid());

  pthread_create(&thread, NULL, run_fifo, NULL);

  pthread_t thread1;
  pthread_create(&thread1, NULL, run_other, NULL);
  sleep(1000);

  done = 1;
  pthread_join(thread, NULL);

  printf("main dies [%ld]\n", gettid());
  return 0;
}
```

Thanks very much for your help.

**Comment by madisongh** [comment]
You're unlikely to find anyone with the necessary expertise on the Linux scheduler or the Android and NVIDIA changes made to the scheduler, to help you with this here.   If this is a general question about the Linux kernel scheduler, you should ask on a mailing list or a forum that has participants that know more about it (maybe on stackoverflow?).  If this is a difference in behavior that's specific to NVIDIA's kernel, you should probably ask this in the NVIDIA developer's forum.  You might also want to search around for "linux kernel scheduler debugging" for some ideas.

**Comment by h2cw2l** [comment]
> You're unlikely to find anyone with the necessary expertise on the Linux scheduler or the Android and NVIDIA changes made to the scheduler, to help you with this here. If this is a general question about the Linux kernel scheduler, you should ask on a mailing list or a forum that has participants that know more about it (maybe on stackoverflow?). If this is a difference in behavior that's specific to NVIDIA's kernel, you should probably ask this in the NVIDIA developer's forum. You might also want to search around for "linux kernel scheduler debugging" for some ideas.

Thanks very much. I will try other ways.
