### ISSUE TITLE
Insmod: ERROR: could not insert module ./overlay.ko: Invalid module format

### ISSUE THREAD

**Issue by lithium555** [OE4T/linux-tegra-4.9#42]
Hi!
How can i fix this trouble? 

Thank you for the future answers. 
```
root@nano:~# cd /lib/modules/4.9.253-tegra/kernel/fs
root@nano:/lib/modules/4.9.253-tegra/kernel/fs# ls -a
.  ..  binfmt_misc.ko  btrfs  cifs  fuse  nfs_common  nfsd  overlayfs
root@nano:/lib/modules/4.9.253-tegra/kernel/fs# cd overlayfs/
root@nano:/lib/modules/4.9.253-tegra/kernel/fs/overlayfs# ls -al
total 100
drwxr-xr-x 2 root root  4096 aug  2  2021 .
drwxr-xr-x 8 root root  4096 aug  2  2021 ..
-rw-r--r-- 1 root root 92760 jul 26  2021 overlay.ko
root@nano:/lib/modules/4.9.253-tegra/kernel/fs/overlayfs# insmod ./overlay.ko 
insmod: ERROR: could not insert module ./overlay.ko: Invalid module format
root@nano:/lib/modules/4.9.253-tegra/kernel/fs/overlayfs# insmod overlay.ko 
insmod: ERROR: could not insert module overlay.ko: Invalid module format
root@nano:/lib/modules/4.9.253-tegra/kernel/fs/overlayfs# 
```

uname -a :
```
 uname -a
Linux nano 4.9.337-tegra #1 SMP PREEMPT Thu Jun 8 21:19:14 PDT 2023 aarch64 aarch64 aarch64 GNU/Linux

```

**Comment by madisongh** [comment]
Did you try a general Internet search for `"linux kernel invalid module format"`?   That should have turned up some helpful information.

Your kernel version (4.9.337-tegra) is different from the version of your kernel modules (4.9.253-tegra).

**Comment by lithium555** [comment]
This is not such easy variant to rebuild kernel. And there are no guarantee, that rebuild will be successful.
I hope, that I can download new kernel version, but Google didn`t help =) . If we speak about NVIDIA documentation -> here we can see only requirement to install 4.9.337-tegra: 
https://docs.nvidia.com/jetson/archives/l4t-archived/l4t-3271/index.html#page/Tegra%20Linux%20Driver%20Package%20Development%20Guide/manifest_jetson_nano.html

I have already found how to rebuild it https://blog.hypriot.com/post/nvidia-jetson-nano-build-kernel-docker-optimized/, but this is last variant in my investigate.

**Comment by madisongh** [comment]
If you are using NVIDIA's Jetson Linux, you shouldn't have to rebuild anything from source, since NVIDIA provides binary packages for their kernel and kernel modules.

The [NVIDIA developer forums](https://forums.developer.nvidia.com/) (under "Jetson and Embedded Systems") would be a better place to ask questions about NVIDIA's JetPack and Jetson Linux.

**Comment by lithium555** [comment]
My uname -a stated 4.9.337, while folders are 4.9.253. I had different versions of Tegra, so I created new image and wrote it on SD card. I saved my own time on fixing errors... Because step by step I had a lot of errors... 

I wrote on Jetson Developer forum this question, maybe somebody in future will have much more time, than me and they will go to another way in this problem: https://forums.developer.nvidia.com/t/insmod-error-could-not-insert-module-overlay-ko-invalid-module-format/270556
